apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/P-S-A-R/argocd.git
    targetRevision: main
    path: applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:              # ✅ Capital 'O' is required
      - CreateNamespace=true  # Optional: auto-create namespace if missing

